class CreateCountries < ActiveRecord::Migration
  def self.up
    create_table :countries do |t|
      t.string :code, :limit => 2, :null => false
      t.string :name_tr, :limit => 50, :null => false
      t.string :name_en, :limit => 50, :null => false
      t.string :code_iso, :limit => 3
      t.string :phone_code, :limit => 5 
    end
    add_index :countries, :code, :unique => true  
q = <<-QQ 
INSERT INTO `countries` VALUES 
('','AF','Afganistan','Afghanistan','AFG',4),
('','AL','Albania','Albania','ALB',8),
('','DZ','Cezayir','Algeria','DZA',12),
('','AD','Andorra','Andorra','AND',20),
('','AO','Angola','Angola','AGO',24),
('','AI','Anguilla','Anguilla','AIA',660),
('','AQ','Antartika','Antarctica',NULL,NULL),
('','AR','Arjantin','Argentina','ARG',32),
('','AM','Ermenistan','Armenia','ARM',51),
('','AW','Aruba','Aruba','ABW',533),
('','AU','Avustralya','Australia','AUS',36),
('','AT','Avustura','Austria','AUT',40),
('','AZ','Azerbeycan','Azerbaijan','AZE',31),
('','BS','Bahamas','Bahamas','BHS',44),
('','BH','Bahrain','Bahrain','BHR',48),
('','BD','Bangladeş','Bangladesh','BGD',50),
('','BB','Barbados','Barbados','BRB',52),
('','BY','Belarus','Belarus','BLR',112),
('','BE','Belçika','Belgium','BEL',56),
('','BZ','Belize','Belize','BLZ',84),
('','BJ','Benin','Benin','BEN',204),
('','BM','Bermuda','Bermuda','BMU',60),
('','BT','Bhutan','Bhutan','BTN',64),
('','BO','Bolivya','Bolivia','BOL',68),
('','BA','Bosna Hersek','Bosnia and Herzegovina','BIH',70),
('','BW','Botswana','Botswana','BWA',72),
('','BV','Bouvet Adası','Bouvet Island',NULL,NULL),
('','BR','Brezilya','Brazil','BRA',76),
('','IO','British Indian Ocean Territory','British Indian Ocean Territory',NULL,NULL),
('','BN','Brunei Darussalam','Brunei Darussalam','BRN',96),
('','BG','Bulgaristan','Bulgaria','BGR',100),
('','BF','Burkina Faso','Burkina Faso','BFA',854),
('','BI','Burundi','Burundi','BDI',108),
('','KH','Kamboçya','Cambodia','KHM',116),
('','CM','Kamerun','Cameroon','CMR',120),
('','CA','Kanada','Canada','CAN',124),
('','CV','Cape Verde','Cape Verde','CPV',132),
('','KY','Cayman Adaları','Cayman Islands','CYM',136),
('','CF','Central African Republic','Central African Republic','CAF',140),
('','TD','Chad','Chad','TCD',148),
('','CL','Şili','Chile','CHL',152),
('','CN','Çin','China','CHN',156),
('','CX','Christmas Adası','Christmas Island',NULL,NULL),
('','CC','Cocos (Keeling) Adaları','Cocos (Keeling) Islands',NULL,NULL),
('','CO','Kolombiya','Colombia','COL',170),
('','KM','Comoros','Comoros','COM',174),
('','CG','Kongo','Congo','COG',178),
('','CD','Kongo Demotratik Cumhuriyeti','Congo, the Democratic Republic of the','COD',180),
('','CK','COOK Adaları','Cook Islands','COK',184),
('','CR','Kosta Rica','Costa Rica','CRI',188),
('','HR','Hırvatistan','Croatia','HRV',191),
('','CU','Küba','Cuba','CUB',192),
('','CY','Kıbrıs','Cyprus','CYP',196),
('','CZ','Çek Cumhuriyeti','Czech Republic','CZE',203),
('','DK','Danimarka','Denmark','DNK',208),
('','DJ','Djibouti','Djibouti','DJI',262),
('','DM','Dominik','Dominica','DMA',212),
('','DO','Dominik Cumhuriyet','Dominican Republic','DOM',214),
('','EC','Ekvador','Ecuador','ECU',218),
('','EG','Mısır','Egypt','EGY',818),
('','SV','El Salvador','El Salvador','SLV',222),
('','GQ','Equatorial Guinea','Equatorial Guinea','GNQ',226),
('','ER','Eritrea','Eritrea','ERI',232),
('','EE','Estonya','Estonia','EST',233),
('','ET','Ethiopia','Ethiopia','ETH',231),
('','FK','Falkland Adaları (Malvinas)','Falkland Islands (Malvinas)','FLK',238),
('','FO','Faroe Adaları','Faroe Islands','FRO',234),
('','FJ','Fiji','Fiji','FJI',242),
('','FI','Finlandiya','Finland','FIN',246),
('','FR','Fransa','France','FRA',250),
('','GA','Gabon','Gabon','GAB',266),
('','GM','Gambia','Gambia','GMB',270),
('','GE','Georgia','Georgia','GEO',268),
('','DE','Almanya','Germany','DEU',276),
('','GH','Gana','Ghana','GHA',288),
('','GI','Gibraltar','Gibraltar','GIB',292),
('','GR','Yunanistan','Greece','GRC',300),
('','GL','Greenland','Greenland','GRL',304),
('','GD','Grenada','Grenada','GRD',308),
('','GP','Guadeloupe','Guadeloupe','GLP',312),
('','GU','Guam','Guam','GUM',316),
('','GT','Guatemala','Guatemala','GTM',320),
('','GN','Guinea','Guinea','GIN',324),
('','GW','Guinea-Bissau','Guinea-Bissau','GNB',624),
('','GY','Guyana','Guyana','GUY',328),
('','HT','Haiti','Haiti','HTI',332),
('','VA','Holy See (Vatican City State)','Holy See (Vatican City State)','VAT',336),
('','HN','Honduras','Honduras','HND',340),
('','HK','Hong Kong','Hong Kong','HKG',344),
('','HU','Macaristan','Hungary','HUN',348),
('','IS','İzlanda','Iceland','ISL',352),
('','IN','Hindistan','India','IND',356),
('','ID','Endonezya','Indonesia','IDN',360),
('','IR','İran','Iran, Islamic Republic of','IRN',364),
('','IQ','Irak','Iraq','IRQ',368),
('','IE','İrlanda','Ireland','IRL',372),
('','IL','İsrail','Israel','ISR',376),
('','IT','İtalya','Italy','ITA',380),
('','JM','Jamaika','Jamaica','JAM',388),
('','JP','Japonya','Japan','JPN',392),
('','JO','Jordan','Jordan','JOR',400),
('','KZ','Kazakistan','Kazakhstan','KAZ',398),
('','KE','Kenya','Kenya','KEN',404),
('','KI','Kiribati','Kiribati','KIR',296),
('','KP','Kore, Democratic Peoples Republic of','Korea, Democratic Peoples Republic of','PRK',408),
('','KR','Kore Cumhuriyeti','Korea, Republic of','KOR',410),
('','KW','Kuveyt','Kuwait','KWT',414),
('','KG','Kırgızistan','Kyrgyzstan','KGZ',417),
('','LV','Latvia','Latvia','LVA',428),
('','LB','Lübnan','Lebanon','LBN',422),
('','LS','Lesotho','Lesotho','LSO',426),
('','LR','Liberya','Liberia','LBR',430),
('','LY','Libyan Arab Jamahiriya','Libyan Arab Jamahiriya','LBY',434),
('','LI','Liechtenstein','Liechtenstein','LIE',438),
('','LT','Litvanya','Lithuania','LTU',440),
('','LU','Lüksemburg','Luxembourg','LUX',442),
('','MO','Macao','Macao','MAC',446),
('','MK','Makedonya','Macedonia, the Former Yugoslav Republic of','MKD',807),
('','MG','Madagaskar','Madagascar','MDG',450),
('','MW','Malawi','Malawi','MWI',454),
('','MY','Malezya','Malaysia','MYS',458),
('','MV','Maldives','Maldives','MDV',462),
('','ML','Mali','Mali','MLI',466),
('','MT','Malta','Malta','MLT',470),
('','MH','Marshall Adaları','Marshall Islands','MHL',584),
('','MQ','Martinique','Martinique','MTQ',474),
('','MR','Mauritania','Mauritania','MRT',478),
('','MU','Mauritius','Mauritius','MUS',480),
('','YT','Mayotte','Mayotte',NULL,NULL),
('','MX','Meksiko','Mexico','MEX',484),
('','FM','Micronesia, Federated States of','Micronesia, Federated States of','FSM',583),
('','MD','Moldova','Moldova, Republic of','MDA',498),
('','MC','Monako','Monaco','MCO',492),
('','MN','Mongolia','Mongolia','MNG',496),
('','MS','Montserrat','Montserrat','MSR',500),
('','MA','Fas','Morocco','MAR',504),
('','MZ','Mozambik','Mozambique','MOZ',508),
('','MM','Myanmar','Myanmar','MMR',104),
('','NA','Namibya','Namibia','NAM',516),
('','NR','Nauru','Nauru','NRU',520),
('','NP','Nepal','Nepal','NPL',524),
('','NL','Hollanda','Netherlands','NLD',528),
('','NZ','Yeni Zellanda','New Zealand','NZL',554),
('','NI','Nikaragua','Nicaragua','NIC',558),
('','NE','Nijer','Niger','NER',562),
('','NG','Nijerya','Nigeria','NGA',566),
('','NU','Niue','Niue','NIU',570),
('','NF','Norfolk Adası','Norfolk Island','NFK',574),
('','MP','Kuzey Mariana Adaları','Northern Mariana Islands','MNP',580),
('','NO','Norveç','Norway','NOR',578),
('','OM','Oman','Oman','OMN',512),
('','PK','Pakistan','Pakistan','PAK',586),
('','PW','Palau','Palau','PLW',585),
('','PS','Palestinian Territory, Occupied','Palestinian Territory, Occupied',NULL,NULL),
('','PA','Panama','Panama','PAN',591),
('','PG','Papua Yeni Gine','Papua New Guinea','PNG',598),
('','PY','Paraguay','Paraguay','PRY',600),
('','PE','Peru','Peru','PER',604),
('','PH','Filipinler','Philippines','PHL',608),
('','PN','Pitcairn','Pitcairn','PCN',612),
('','PL','Polonya','Poland','POL',616),
('','PT','Portekiz','Portugal','PRT',620),
('','PR','Porto Riko','Puerto Rico','PRI',630),
('','QA','Katar','Qatar','QAT',634),
('','RE','Reunion','Reunion','REU',638),
('','RO','Romanya','Romania','ROM',642),
('','RU','Rusya Federasyonu','Russian Federation','RUS',643),
('','RW','Rwanda','Rwanda','RWA',646),
('','WS','Samoa','Samoa','WSM',882),
('','SM','San Marino','San Marino','SMR',674),
('','SA','Suudi Arabistan','Saudi Arabia','SAU',682),
('','SN','Senegal','Senegal','SEN',686),
('','SG','Singapur','Singapore','SGP',702),
('','SK','Slovakya','Slovakia','SVK',703),
('','SI','Slovenya','Slovenia','SVN',705),
('','SB','Solomon Adaları','Solomon Islands','SLB',90),
('','SO','Somali','Somalia','SOM',706),
('','ZA','Kuzey Afrika','South Africa','ZAF',710),
('','ES','İspanya','Spain','ESP',724),
('','LK','Sri Lanka','Sri Lanka','LKA',144),
('','SD','Sudan','Sudan','SDN',736),
('','SR','Suriname','Suriname','SUR',740),
('','SZ','Swaziland','Swaziland','SWZ',748),
('','SE','İsveç','Sweden','SWE',752),
('','CH','İsviçre','Switzerland','CHE',756),
('','SY','Syrian Arab Republic','Syrian Arab Republic','SYR',760),
('','TW','Taiwan','Taiwan, Province of China','TWN',158),
('','TJ','Tacikistan','Tajikistan','TJK',762),
('','TZ','Tanzanya, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA',834),
('','TH','Tayland','Thailand','THA',764),
('','TL','Timor-leste','Timor-Leste',NULL,NULL),
('','TG','Togo','Togo','TGO',768),
('','TK','Tokelau','Tokelau','TKL',772),
('','TO','Tonga','Tonga','TON',776),
('','TN','Tunus','Tunisia','TUN',788),
('','TR','Türkiye','Turkey','TUR',792),
('','TM','Türkmenistan','Turkmenistan','TKM',795),
('','TC','Turks and Caicos Islands','Turks and Caicos Islands','TCA',796),
('','TV','Tuvalu','Tuvalu','TUV',798),
('','UG','Uganda','Uganda','UGA',800),
('','UA','Ukrayna','Ukraine','UKR',804),
('','AE','Birleşik Arap Emirlikleri','United Arab Emirates','ARE',784),
('','GB','İngiltere','United Kingdom','GBR',826),
('','US','Amerika Birleşik Devletleri','United States','USA',840),
('','UY','Uruguay','Uruguay','URY',858),
('','UZ','Özbekistan','Uzbekistan','UZB',860),
('','VU','Vanuatu','Vanuatu','VUT',548),
('','VE','Venezuela','Venezuela','VEN',862),
('','VN','Viet Nam','Viet Nam','VNM',704),
('','EH','Batı Sahara','Western Sahara','ESH',732),
('','YE','Yemen','Yemen','YEM',887),
('','ZM','Zambia','Zambia','ZMB',894),
('','ZW','Zimbabve','Zimbabwe','ZWE',716);

QQ
    
    ActiveRecord::Base.connection.execute(q)

    #a = [
    #]
    #a.each do |item|
    #  Country.create!(:name => item[0], :code => item[1])
    #end
  end

  def self.down
    drop_table :countries
  end
end
